import os
import json
import time
from typing import List, Dict
from groq import Groq
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

# --- CONFIGURATION ---
API_KEY = os.getenv("GROQ_API_KEY", "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")
client = Groq(api_key=API_KEY)
OUTPUT_DIR = "reports"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- DOCTOR REPORT TEMPLATE ---
DOCTOR_TEMPLATE = """
You are a Medical Scribe AI assisting a Dermatologist.
Analyze the FULL consultation history and ALL image analyses provided.

=====================
CRITICAL INSTRUCTION: MULTIPLE IMAGES
=====================
The patient has uploaded **{image_count} image(s)**.
1. **Consolidate:** Your "Visual Analysis" section MUST summarize the findings for **EVERY** image upload chronologically.
   - Example format: "Scan 1: [Condition A 50%]. Scan 2: [Condition B 40%]."
2. **Synthesize:** In the "Differential Diagnosis," consider the ENTIRE set of data. 
   - If findings conflict (e.g., Scan 1 says Eczema, Scan 2 says Acne), mention BOTH possibilities or explain the discrepancy (e.g., "different lighting" or "multiple lesion types").

=====================
JSON STRUCTURE
=====================
{{
  "patient_id": "string",
  "consultation_date": "string (YYYY-MM-DD)",
  "chief_complaint": "Concise summary of patient's symptoms.",
  "history_of_present_illness": "Narrative of the consultation, mentioning that multiple images were reviewed if applicable.",
  "visual_analysis_raw": ["Scan 1: List top %...", "Scan 2: List top %..."], 
  "differential_diagnosis": "Top hypotheses considering ALL images.",
  "recommended_plan": "Next steps (Biopsy, etc)."
}}

=====================
INPUT DATA
=====================
User Chat History:
{history}

ALL Image Analyses (Chronological):
{system_analysis}
"""


def create_pdf(data: dict, filename: str):
    doc = SimpleDocTemplate(filename, pagesize=LETTER)
    styles = getSampleStyleSheet()
    story = []

    # --- STYLES ---
    title_style = ParagraphStyle('ReportTitle', parent=styles['Heading1'], fontSize=24,
                                 textColor=colors.HexColor("#059669"), spaceAfter=20, alignment=1)
    header_style = ParagraphStyle('SectionHeader', parent=styles['Heading2'], fontSize=12, textColor=colors.white,
                                  backColor=colors.HexColor("#059669"), borderPadding=(5, 5, 5, 5), spaceBefore=12,
                                  spaceAfter=6)
    body_style = styles['BodyText']
    body_style.spaceAfter = 12

    # --- TITLE & META ---
    story.append(Paragraph("PRELIMINARY DERMATOLOGY REPORT", title_style))
    story.append(Spacer(1, 12))

    meta_data = [
        ["Patient Ref:", data.get('patient_id', 'N/A'), "Date:", data.get('consultation_date', 'N/A')],
        ["Generated By:", "HealthBuddy AI Scribe", "Confidentiality:", "Private Medical Record"]
    ]
    t = Table(meta_data, colWidths=[1.5 * inch, 2 * inch, 1 * inch, 2 * inch])
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.darkgrey),
        ('LINEBELOW', (0, 0), (-1, -1), 1, colors.lightgrey),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(t)
    story.append(Spacer(1, 20))

    # --- SECTIONS ---
    def add_section(title, content):
        story.append(Paragraph(title.upper(), header_style))
        if isinstance(content, list):
            content = "<br/>".join([f"- {item}" for item in content])
        story.append(Paragraph(str(content), body_style))

    add_section("Chief Complaint", data.get("chief_complaint", "N/A"))
    add_section("History of Present Illness", data.get("history_of_present_illness", "N/A"))

    # VISUAL ANALYSIS (Handles Multiple Scans)
    story.append(Paragraph("AUTOMATED VISUAL ANALYSIS (ALL SCANS)", header_style))
    visual_raw = data.get('visual_analysis_raw', 'N/A')

    # If it's a list (Scan 1, Scan 2...), format it nicely
    if isinstance(visual_raw, list):
        for item in visual_raw:
            # Make "Scan X:" bold for readability
            formatted_item = item.replace("Scan", "<b>Scan</b>")
            story.append(Paragraph(formatted_item, body_style))
    else:
        story.append(Paragraph(str(visual_raw), body_style))

    add_section("Differential Diagnosis", data.get("differential_diagnosis", "N/A"))
    add_section("Suggested Management Plan", data.get("recommended_plan", "N/A"))

    # --- DISCLAIMER ---
    story.append(Spacer(1, 40))
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.grey,
                                      alignment=1)
    story.append(Paragraph(
        "<b>DISCLAIMER:</b> This report is generated by AI. It is NOT a definitive diagnosis. All findings must be verified clinically.",
        disclaimer_style))

    doc.build(story)


def generate_doctor_report(chat_id: str, history: List[Dict], system_analysis: str) -> str:
    print(f"--- Generating PDF Report for Chat {chat_id} ---")

    history_text = "\n".join([f"{m.get('role', 'User')}: {m.get('text', '')}" for m in history])

    # Count how many images based on our separator
    image_count = system_analysis.count("--- IMAGE SCAN")

    prompt = DOCTOR_TEMPLATE.format(
        image_count=image_count if image_count > 0 else 0,
        history=history_text,
        system_analysis=system_analysis
    )

    try:
        completion = client.chat.completions.create(
            messages=[{"role": "system", "content": prompt}],
            model="llama-3.3-70b-versatile",
            temperature=0.2,
            response_format={"type": "json_object"}
        )

        content_str = completion.choices[0].message.content
        report_data = json.loads(content_str)

        if "patient_id" not in report_data or not report_data["patient_id"]: report_data["patient_id"] = chat_id
        if "consultation_date" not in report_data: report_data["consultation_date"] = time.strftime("%Y-%m-%d")

        filename = f"Medical_Report_{chat_id}_{int(time.time())}.pdf"
        file_path = os.path.join(OUTPUT_DIR, filename)

        create_pdf(report_data, file_path)
        return file_path

    except Exception as e:
        print(f"Report Generation Error: {e}")
        return None